global_costmap:
  global_frame: map
  robot_base_frame: X1/base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 16.0
  height: 16.0
  resolution: 0.05
